// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5EywTrtVtRx97gxpNTMGIJQnOxomPoQU',
    appId: '1:253475619117:web:71dfb156996f458f54d3a4',
    messagingSenderId: '253475619117',
    projectId: 'flutter-test-message',
    authDomain: 'flutter-test-message.firebaseapp.com',
    storageBucket: 'flutter-test-message.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdEJAmV8WEQxiTcZfoLzKAk0dmn-wQEj8',
    appId: '1:253475619117:android:3c755e09c2e20ac954d3a4',
    messagingSenderId: '253475619117',
    projectId: 'flutter-test-message',
    storageBucket: 'flutter-test-message.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWYm8uADY4CP2OlBEPZR2RZukrv7OHYZU',
    appId: '1:253475619117:ios:cb51822a87b3997654d3a4',
    messagingSenderId: '253475619117',
    projectId: 'flutter-test-message',
    storageBucket: 'flutter-test-message.appspot.com',
    androidClientId: '253475619117-07bp313n190vj94haaq8ek85a4jlmeer.apps.googleusercontent.com',
    iosClientId: '253475619117-91n6tetgus48drbvqe0dbeoa759mfgc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWYm8uADY4CP2OlBEPZR2RZukrv7OHYZU',
    appId: '1:253475619117:ios:cb51822a87b3997654d3a4',
    messagingSenderId: '253475619117',
    projectId: 'flutter-test-message',
    storageBucket: 'flutter-test-message.appspot.com',
    androidClientId: '253475619117-07bp313n190vj94haaq8ek85a4jlmeer.apps.googleusercontent.com',
    iosClientId: '253475619117-91n6tetgus48drbvqe0dbeoa759mfgc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseChatApp',
  );
}
